pipeline{
    agent any
        stages{
            stage("First Stage"){
                steps{
                    sh'''
                        echo "first build"
                    '''
                }
            }
            stage("Second Stage"){
                steps{
                    sh '''
                        echo "Second build"
                    '''
             }
        }
            stage("Third Stage"){
                steps{
                    sh '''
                        echo "Third build
                    '''
                }
            }
   }
}
