pipeline{
    stage any
        stages{
            stage("First Build")
                steps{
                    sh'''
                    echo "building new"
                    '''
                }
        }
}