pipeline{
    agent any
        stages{
            stage("First stage"){
                steps{
                    sh'''
                        echo "first build"
                    '''
                }
            }
            stage("Second Stage"){
                steps{
                sh '''
                    echo "Second build"
                    '''
             }
        }
    }
}
